version: "3.7"

services:
  database:
    image: postgres
    ports:
      - '5454:5432'
    container_name: ecommerce
    restart: always
    volumes:
      - ecommerce-disk:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ecommerce

volumes:
  ecommerce-disk: